AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::LanguageExtensions

Parameters:

  CollectionNames:
    Type: CommaDelimitedList

Resources:

  # TODO: Nice name?
  Topic:
    Type: AWS::SNS::Topic

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref Topic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sns:Subscribe
              - sns:Receive
            Resource: !Ref Topic
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                SNS:Protocol:
                  - sqs
                  - lambda

  "Fn::ForEach::CollectionNamesLoop":
    - CollectionName
    - !Ref CollectionNames
    - "Sqs&{CollectionName}":
        Type: AWS::CloudFormation::Stack
        Properties:
          Parameters:
            TopicArn: !Ref Topic
          TemplateURL: stacks/sqs-to-sns-cf.yml

Outputs:

  TopicArn:
    Description: ARN of the SNS Topic
    Value: !Ref Topic
