AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::LanguageExtensions

Parameters:

  CollectionNames:
    Type: CommaDelimitedList

Resources:

  # TODO: Nice name?
  Topic:
    Type: AWS::SNS::Topic

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref Topic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sns:Subscribe
              - sns:Receive
            Resource: !Ref Topic
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                SNS:Protocol:
                  - sqs
                  - lambda

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600

  PipeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: pipes.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PipeAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref Topic

  "Fn::ForEach::CollectionNamesLoop":
    - CollectionName
    - !Ref CollectionNames
    - "Sqs&{CollectionName}":
        Type: AWS::CloudFormation::Stack
        Properties:
          Parameters:
            TopicArn: !Ref Topic
            PipeExecutionRoleArn: !GetAtt PipeExecutionRole.Arn
            DeadLetterQueueArn: !GetAtt DeadLetterQueue.Arn
          TemplateURL: stacks/sqs-to-sns-cf.yml

Outputs:

  TopicArn:
    Description: ARN of the SNS Topic
    Value: !Ref Topic
