AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EcrImageUri:
    Description: ECR image URI
    Type: String

  CmrDomainName:
    Description: CMR search API domain name
    Type: String
    Default: cmr.earthdata.nasa.gov
    AllowedValues:
      - cmr.earthdata.nasa.gov
      - cmr.uat.earthdata.nasa.gov

  CmrProvider:
    Description: CMR provider to use when searching for new granules
    Type: String
    Default: ASF

Resources:

  # TODO: Nice name?
  Topic:
    Type: AWS::SNS::Topic

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref Topic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sns:Subscribe
            Resource: !Ref Topic
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                SNS:Protocol:
                  - sqs
                  - lambda

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Lambda}"
      RetentionInDays: 90

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
        - PolicyName: policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref Topic
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                Resource: !GetAtt Table.Arn
              - Effect: Allow
                Action:
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetAuthorizationToken
                  - ecr:GetDownloadUrlForLayer
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*"

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command:
          - cmr_notifier.main.lambda_handler
      Code:
        ImageUri: !Ref EcrImageUri
      Environment:
        Variables:
          TOPIC_ARN: !Ref Topic
          TABLE_NAME: !Ref Table
          CMR_DOMAIN_NAME: !Ref CmrDomainName
          CMR_PROVIDER: !Ref CmrProvider
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Timeout: 900

  EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref Lambda
      Qualifier: $LATEST
      MaximumRetryAttempts: 0

  Schedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(1 minute)"
      Targets:
        - Arn: !GetAtt Lambda.Arn
          Id: schedule
          Input: '{"window_in_seconds": 120}'

  EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Lambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Schedule.Arn


  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 10
      AttributeDefinitions:
        - AttributeName: granule_ur
          AttributeType: S
        - AttributeName: sent_at
          AttributeType: S
      KeySchema:
        - AttributeName: granule_ur
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: sent_at
          KeySchema:
            - AttributeName: sent_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:

  TopicArn:
    Description: ARN of the SNS Topic
    Value: !Ref Topic
