AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EcrImageUri:
    Description: ECR image URI
    Type: String

  CmrDomainName:
    Description: CMR search API domain name
    Type: String
    Default: cmr.earthdata.nasa.gov
    AllowedValues:
      - cmr.earthdata.nasa.gov
      - cmr.uat.earthdata.nasa.gov

  CmrProvider:
    Description: CMR provider to use when searching for new granules
    Type: String
    Default: ASF

Resources:

  Sentinel1Topic:
    Type: AWS::SNS::Topic
    Properties:
      # Note: The only other parameter that requires replacement on update is FifoTopic, so this shan't be troublesome.
      #       See: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-sns-topic.html
      TopicName: !Sub '${CmrProvider}-sentinel1-${AWS::StackName}'

  Sentinel1TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref Sentinel1Topic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sns:Subscribe
            Resource: !Ref Sentinel1Topic
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                SNS:Protocol:
                  - sqs
                  - lambda

  NisarTopic:
    Type: AWS::SNS::Topic
    Properties:
      # Note: The only other parameter that requires replacement on update is FifoTopic, so this shan't be troublesome.
      #       See: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-sns-topic.html
      TopicName: !Sub '${CmrProvider}-nisar-${AWS::StackName}'

  NisarTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref NisarTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sns:Subscribe
            Resource: !Ref NisarTopic
            Principal:
              AWS: "*"
            Condition:
              StringEquals:
                SNS:Protocol:
                  - sqs
                  - lambda

  Sentinel1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Sentinel1Lambda}"
      RetentionInDays: 90

  NisarLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NisarLambda}"
      RetentionInDays: 90

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      Policies:
        - PolicyName: policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - Effect: Allow
                Action: sns:Publish
                Resource: 
                  - !Ref Sentinel1Topic
                  - !Ref NisarTopic
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                Resource: !GetAtt Table.Arn
              - Effect: Allow
                Action:
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetAuthorizationToken
                  - ecr:GetDownloadUrlForLayer
                Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*"

  Sentinel1Lambda:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command:
          - cmr_notifier.main.lambda_handler
      Code:
        ImageUri: !Ref EcrImageUri
      Environment:
        Variables:
          TOPIC_ARN: !Ref Sentinel1Topic
          TABLE_NAME: !Ref Table
          CMR_DOMAIN_NAME: !Ref CmrDomainName
          CMR_PROVIDER: !Ref CmrProvider
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Timeout: 900

  NisarLambda:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command:
          - cmr_notifier.main.lambda_handler
      Code:
        ImageUri: !Ref EcrImageUri
      Environment:
        Variables:
          TOPIC_ARN: !Ref NisarTopic
          TABLE_NAME: !Ref Table
          CMR_DOMAIN_NAME: !Ref CmrDomainName
          CMR_PROVIDER: !Ref CmrProvider
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Timeout: 900

  Sentinel1EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref Sentinel1Lambda
      Qualifier: $LATEST
      MaximumRetryAttempts: 0

  Sentinel1Schedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(1 minute)"
      Targets:
        - Arn: !GetAtt Sentinel1Lambda.Arn
          Id: schedule
          Input: '{"window_in_seconds": 120}'

  Sentinel1EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Sentinel1Lambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Sentinel1Schedule.Arn

  NisarEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref NisarLambda
      Qualifier: $LATEST
      MaximumRetryAttempts: 0

  NisarSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(1 minute)"
      Targets:
        - Arn: !GetAtt NisarLambda.Arn
          Id: schedule
          Input: '{"window_in_seconds": 120}'

  NisarEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt NisarLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt NisarSchedule.Arn

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 10
      AttributeDefinitions:
        - AttributeName: granule_ur
          AttributeType: S
      KeySchema:
        - AttributeName: granule_ur
          KeyType: HASH

Outputs:
  Sentinel1TopicArn:
    Description: ARN of the Sentinel-1 SNS Topic
    Value: !Ref Sentinel1Topic
  NisarTopicArn:
    Description: ARN of the NISAR SNS Topic
    Value: !Ref NisarTopic
