AWSTemplateFormatVersion: 2010-09-09

Parameters:

  TopicArn:
    Type: String

  PipeExecutionRoleArn:
    Type: String

  DeadLetterQueueArn:
    Type: String

Resources:

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !Ref DeadLetterQueueArn
        maxReceiveCount: 3

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt Queue.Arn
      Queues:
        - !Ref Queue

  Pipe:
    Type: AWS::Pipes::Pipe
    Properties:
      RoleArn: !Ref PipeExecutionRoleArn
      Source: !GetAtt Queue.Arn
      Target: !Ref TopicArn

Outputs:

  QueueUrl:
    Description: URL of the SQS Queue
    Value: !Ref Queue
