name: Build image and deploy
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  version-info:
    uses: ASFHyP3/actions/.github/workflows/reusable-pixi-version-info.yml@v0.22.0
    permissions:
      contents: read

  dockerize:
    needs: version-info
    uses: ASFHyP3/actions/.github/workflows/reusable-docker-ecr.yml@v0.22.0
    with:
      fetch_depth: 1
      aws_region: ${{ vars.AWS_REGION }}
      role_to_assume: ${{ vars.OIDC_ROLE_ARN }}
      ecr_registry: ${{ vars.ECR_REGISTRY }}
      version_tag: ${{ needs.version-info.outputs.version_tag }}
      build_args: "SETUPTOOLS_SCM_PRETEND_VERSION=${{ needs.version-info.outputs.version }}"
      platforms: 'linux/amd64'
      provenance: false
    permissions:
      contents: read
      id-token: write


  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - version-info
      - dockerize
    strategy:
      matrix:
        maturity:
          - ${{ contains(needs.version-info.outputs.version_tag, '.dev') && 'test' || 'prod' }}
        dataset:
          - sentinel1
          - nisar
    concurrency:
      group: deploy-${{ matrix.dataset }}-${{ matrix.maturity }}
    environment: ${{ matrix.dataset }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Package and deploy
        shell: bash
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yml \
            --stack-name=${{ vars.STACK_PREFIX }}-${{ matrix.maturity }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              EcrImageUri=${{ needs.dockerize.outputs.image_uri }} \
              CmrDomainName=${{ vars.CMR_DOMAIN_NAME }} \
              CmrProvider=${{ vars.CMR_PROVIDER }} \
              TopicName=${{ vars.TOPIC_PREFIX }}-${{ matrix.maturity }}
